//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playhouse.UI.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsUI() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Playhouse.UI.Resources.Localization.StringsUI", typeof(StringsUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        public static string BotPropertyID {
            get {
                return ResourceManager.GetString("BotPropertyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string BotPropertyName {
            get {
                return ResourceManager.GetString("BotPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create bot.
        /// </summary>
        public static string BoxCreateBotHeader {
            get {
                return ResourceManager.GetString("BoxCreateBotHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete bot.
        /// </summary>
        public static string BoxDeleteBotHeader {
            get {
                return ResourceManager.GetString("BoxDeleteBotHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        public static string BoxInformationProfileHeader {
            get {
                return ResourceManager.GetString("BoxInformationProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other.
        /// </summary>
        public static string BoxOtherProfileHeader {
            get {
                return ResourceManager.GetString("BoxOtherProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Running tasks.
        /// </summary>
        public static string BoxRunningTasksHeader {
            get {
                return ResourceManager.GetString("BoxRunningTasksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run task.
        /// </summary>
        public static string BoxRunTaskHeader {
            get {
                return ResourceManager.GetString("BoxRunTaskHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Storage.
        /// </summary>
        public static string BoxStorageProfileHeader {
            get {
                return ResourceManager.GetString("BoxStorageProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        public static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browse...
        /// </summary>
        public static string ButtonSearchFile {
            get {
                return ResourceManager.GetString("ButtonSearchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run.
        /// </summary>
        public static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm.
        /// </summary>
        public static string CheckBoxConfirm {
            get {
                return ResourceManager.GetString("CheckBoxConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable Chromium sandbox.
        /// </summary>
        public static string CheckBoxEnableChromiumSandbox {
            get {
                return ResourceManager.GetString("CheckBoxEnableChromiumSandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Headless mode.
        /// </summary>
        public static string CheckBoxHeadlessMode {
            get {
                return ResourceManager.GetString("CheckBoxHeadlessMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accept all downloads.
        /// </summary>
        public static string LabelAcceptDownloadsProfile {
            get {
                return ResourceManager.GetString("LabelAcceptDownloadsProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bot name:.
        /// </summary>
        public static string LabelBotName {
            get {
                return ResourceManager.GetString("LabelBotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download path.
        /// </summary>
        public static string LabelDownloadPath {
            get {
                return ResourceManager.GetString("LabelDownloadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile name:.
        /// </summary>
        public static string LabelProfileName {
            get {
                return ResourceManager.GetString("LabelProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select bot.
        /// </summary>
        public static string LabelSelectBot {
            get {
                return ResourceManager.GetString("LabelSelectBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select browser.
        /// </summary>
        public static string LabelSelectBrowser {
            get {
                return ResourceManager.GetString("LabelSelectBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Profile.
        /// </summary>
        public static string LabelSelectProfile {
            get {
                return ResourceManager.GetString("LabelSelectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Profiles.
        /// </summary>
        public static string LabelSelectProfiles {
            get {
                return ResourceManager.GetString("LabelSelectProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bots.
        /// </summary>
        public static string LabelSettingsBots {
            get {
                return ResourceManager.GetString("LabelSettingsBots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Specifies the name of the objects if it is not specified by the user..
        /// </summary>
        public static string LabelSettingsDescriptionDefaultNaming {
            get {
                return ResourceManager.GetString("LabelSettingsDescriptionDefaultNaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Locating files in a computer&apos;s file system..
        /// </summary>
        public static string LabelSettingsDescriptionFileLocation {
            get {
                return ResourceManager.GetString("LabelSettingsDescriptionFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browsers and their channels that need to be installed..
        /// </summary>
        public static string LabelSettingsDescriptionInstalledBrowsers {
            get {
                return ResourceManager.GetString("LabelSettingsDescriptionInstalledBrowsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language of user interface display..
        /// </summary>
        public static string LabelSettingsDescriptionLanguage {
            get {
                return ResourceManager.GetString("LabelSettingsDescriptionLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default naming.
        /// </summary>
        public static string LabelSettingsHeaderDefaultNaming {
            get {
                return ResourceManager.GetString("LabelSettingsHeaderDefaultNaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File location.
        /// </summary>
        public static string LabelSettingsHeaderFileLocation {
            get {
                return ResourceManager.GetString("LabelSettingsHeaderFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installed browsers.
        /// </summary>
        public static string LabelSettingsHeaderInstalledBrowsers {
            get {
                return ResourceManager.GetString("LabelSettingsHeaderInstalledBrowsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string LabelSettingsHeaderLanguage {
            get {
                return ResourceManager.GetString("LabelSettingsHeaderLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profiles.
        /// </summary>
        public static string LabelSettingsProfiles {
            get {
                return ResourceManager.GetString("LabelSettingsProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slow motion (milliseconds).
        /// </summary>
        public static string LabelSlowMo {
            get {
                return ResourceManager.GetString("LabelSlowMo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loaded profile:.
        /// </summary>
        public static string LabelStatusLoadedProfile {
            get {
                return ResourceManager.GetString("LabelStatusLoadedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of profiles:.
        /// </summary>
        public static string LabelStatusNumberOfProfiles {
            get {
                return ResourceManager.GetString("LabelStatusNumberOfProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        public static string ProfilePropertyID {
            get {
                return ResourceManager.GetString("ProfilePropertyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string ProfilePropertyName {
            get {
                return ResourceManager.GetString("ProfilePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bots.
        /// </summary>
        public static string TabBotsHeader {
            get {
                return ResourceManager.GetString("TabBotsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profiles.
        /// </summary>
        public static string TabProfilesHeader {
            get {
                return ResourceManager.GetString("TabProfilesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run.
        /// </summary>
        public static string TabRunHeader {
            get {
                return ResourceManager.GetString("TabRunHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string TabSettingsHeader {
            get {
                return ResourceManager.GetString("TabSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string TextBoxWatermarkProfilesSearh {
            get {
                return ResourceManager.GetString("TextBoxWatermarkProfilesSearh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Playhouse - Constructor Bot.
        /// </summary>
        public static string WindowConstructorBotTitle {
            get {
                return ResourceManager.GetString("WindowConstructorBotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Playhouse.
        /// </summary>
        public static string WindowMainTitle {
            get {
                return ResourceManager.GetString("WindowMainTitle", resourceCulture);
            }
        }
    }
}
