//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playhouse.Settings.Domain.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Playhouse.Settings.Domain.Resources.Strings.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The browser has already been added..
        /// </summary>
        internal static string ApplicationSettingsBrowserAlreadyAdded {
            get {
                return ResourceManager.GetString("ApplicationSettingsBrowserAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser is missing..
        /// </summary>
        internal static string ApplicationSettingsBrowserMissing {
            get {
                return ResourceManager.GetString("ApplicationSettingsBrowserMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser not specified..
        /// </summary>
        internal static string ApplicationSettingsBrowserNotSpecified {
            get {
                return ResourceManager.GetString("ApplicationSettingsBrowserNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The channel has already been added..
        /// </summary>
        internal static string ApplicationSettingsChannelAlreadyAdded {
            get {
                return ResourceManager.GetString("ApplicationSettingsChannelAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The channel is missing..
        /// </summary>
        internal static string ApplicationSettingsChannelMissing {
            get {
                return ResourceManager.GetString("ApplicationSettingsChannelMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Channel not specified..
        /// </summary>
        internal static string ApplicationSettingsChannelNotSpecified {
            get {
                return ResourceManager.GetString("ApplicationSettingsChannelNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Culture not specified..
        /// </summary>
        internal static string ApplicationSettingsCultureNotSpecified {
            get {
                return ResourceManager.GetString("ApplicationSettingsCultureNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The path to the data directory is not specified..
        /// </summary>
        internal static string ApplicationSettingsDirectoryNotSpecified {
            get {
                return ResourceManager.GetString("ApplicationSettingsDirectoryNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New culture value is identical to the current one..
        /// </summary>
        internal static string ApplicationSettingsIdenticalCultureAlreadySet {
            get {
                return ResourceManager.GetString("ApplicationSettingsIdenticalCultureAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New data path is identical to the current one..
        /// </summary>
        internal static string ApplicationSettingsIdenticalPathToDataAlreadySet {
            get {
                return ResourceManager.GetString("ApplicationSettingsIdenticalPathToDataAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The culture is not supported by the application..
        /// </summary>
        internal static string CultureIsNotSupported {
            get {
                return ResourceManager.GetString("CultureIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Culture not specified..
        /// </summary>
        internal static string CultureNotSpecified {
            get {
                return ResourceManager.GetString("CultureNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The directory path contains invalid characters..
        /// </summary>
        internal static string DirectoryPathContainsInvalidChars {
            get {
                return ResourceManager.GetString("DirectoryPathContainsInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The directory path must be absolute..
        /// </summary>
        internal static string DirectoryPathMustAbsolute {
            get {
                return ResourceManager.GetString("DirectoryPathMustAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The directory path is not specified..
        /// </summary>
        internal static string DirectoryPathNotSpecified {
            get {
                return ResourceManager.GetString("DirectoryPathNotSpecified", resourceCulture);
            }
        }
    }
}
