//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playhouse.Settings.Domain.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Playhouse.Settings.Domain.Resources.Strings.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser &quot;{0} &quot;has already been added..
        /// </summary>
        internal static string ApplicationSettingsBrowserExist {
            get {
                return ResourceManager.GetString("ApplicationSettingsBrowserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser &quot;{0}&quot; is missing..
        /// </summary>
        internal static string ApplicationSettingsBrowserNotFound {
            get {
                return ResourceManager.GetString("ApplicationSettingsBrowserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser not specified..
        /// </summary>
        internal static string ApplicationSettingsBrowserNotSpecified {
            get {
                return ResourceManager.GetString("ApplicationSettingsBrowserNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Channel &quot;{0}&quot; of browser &quot;{1}&quot; has already been added..
        /// </summary>
        internal static string ApplicationSettingsChannelExist {
            get {
                return ResourceManager.GetString("ApplicationSettingsChannelExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Channel &quot;{0}&quot; of browser &quot;{1}&quot; is missing..
        /// </summary>
        internal static string ApplicationSettingsChannelNotFound {
            get {
                return ResourceManager.GetString("ApplicationSettingsChannelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Channel not specified..
        /// </summary>
        internal static string ApplicationSettingsChannelNotSpecified {
            get {
                return ResourceManager.GetString("ApplicationSettingsChannelNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The application language is not specified..
        /// </summary>
        internal static string ApplicationSettingsLanguageNotSpecified {
            get {
                return ResourceManager.GetString("ApplicationSettingsLanguageNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language &quot;{0}&quot; is already in use..
        /// </summary>
        internal static string ApplicationSettingsLanguageSame {
            get {
                return ResourceManager.GetString("ApplicationSettingsLanguageSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The path to the data directory is not specified..
        /// </summary>
        internal static string ApplicationSettingsPathToDataNotSpecified {
            get {
                return ResourceManager.GetString("ApplicationSettingsPathToDataNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The data path &quot;{0}&quot; is already in use by this application..
        /// </summary>
        internal static string ApplicationSettingsPathToDataSame {
            get {
                return ResourceManager.GetString("ApplicationSettingsPathToDataSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language &apos;{0}&apos; is not supported by the application..
        /// </summary>
        internal static string CultureCodeMustBeSupported {
            get {
                return ResourceManager.GetString("CultureCodeMustBeSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The user interface language is not specified..
        /// </summary>
        internal static string CultureCodeMustNotBeEmpty {
            get {
                return ResourceManager.GetString("CultureCodeMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The directory path must be absolute..
        /// </summary>
        internal static string DirectoryPathMustBeAbsolute {
            get {
                return ResourceManager.GetString("DirectoryPathMustBeAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The directory path is not specified..
        /// </summary>
        internal static string DirectoryPathMustNotBeEmpty {
            get {
                return ResourceManager.GetString("DirectoryPathMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The directory path contains invalid characters..
        /// </summary>
        internal static string DirectoryPathMustNotContainInvalidChars {
            get {
                return ResourceManager.GetString("DirectoryPathMustNotContainInvalidChars", resourceCulture);
            }
        }
    }
}
