//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playhouse.UI.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsUI() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Playhouse.UI.Resources.Localization.StringsUI", typeof(StringsUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на id.
        /// </summary>
        public static string Bot_Id {
            get {
                return ResourceManager.GetString("Bot_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Bot_Name {
            get {
                return ResourceManager.GetString("Bot_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Actions:.
        /// </summary>
        public static string BotConstructorWindow_Actions_Text {
            get {
                return ResourceManager.GetString("BotConstructorWindow_Actions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action Settings.
        /// </summary>
        public static string BotConstructorWindow_ActionSettings_Header {
            get {
                return ResourceManager.GetString("BotConstructorWindow_ActionSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string BotConstructorWindow_Save {
            get {
                return ResourceManager.GetString("BotConstructorWindow_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Playhouse - Constructor Bot.
        /// </summary>
        public static string BotConstructorWindow_Title {
            get {
                return ResourceManager.GetString("BotConstructorWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        public static string Browser_Id {
            get {
                return ResourceManager.GetString("Browser_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Browser_Name {
            get {
                return ResourceManager.GetString("Browser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser context created.
        /// </summary>
        public static string BrowserContextCreatedBotActionViewModel_Master_Title {
            get {
                return ResourceManager.GetString("BrowserContextCreatedBotActionViewModel_Master_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bots.
        /// </summary>
        public static string MainWindow_BotsTab_Header {
            get {
                return ResourceManager.GetString("MainWindow_BotsTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bot name:.
        /// </summary>
        public static string MainWindow_CreateBotGroup_BotName {
            get {
                return ResourceManager.GetString("MainWindow_CreateBotGroup_BotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        public static string MainWindow_CreateBotGroup_Create {
            get {
                return ResourceManager.GetString("MainWindow_CreateBotGroup_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create bot.
        /// </summary>
        public static string MainWindow_CreateBotGroup_Header {
            get {
                return ResourceManager.GetString("MainWindow_CreateBotGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select browser:.
        /// </summary>
        public static string MainWindow_CreateBotGroup_SelectBrowserType {
            get {
                return ResourceManager.GetString("MainWindow_CreateBotGroup_SelectBrowserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Profile:.
        /// </summary>
        public static string MainWindow_CreateBotGroup_SelectProfile {
            get {
                return ResourceManager.GetString("MainWindow_CreateBotGroup_SelectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm.
        /// </summary>
        public static string MainWindow_DeleteBotGroup_Confirm {
            get {
                return ResourceManager.GetString("MainWindow_DeleteBotGroup_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string MainWindow_DeleteBotGroup_Delete {
            get {
                return ResourceManager.GetString("MainWindow_DeleteBotGroup_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete bot.
        /// </summary>
        public static string MainWindow_DeleteBotGroup_Header {
            get {
                return ResourceManager.GetString("MainWindow_DeleteBotGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select bot:.
        /// </summary>
        public static string MainWindow_DeleteBotGroup_SelectBot {
            get {
                return ResourceManager.GetString("MainWindow_DeleteBotGroup_SelectBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string MainWindow_ProfilesControl_Add {
            get {
                return ResourceManager.GetString("MainWindow_ProfilesControl_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string MainWindow_ProfilesControl_Cancel {
            get {
                return ResourceManager.GetString("MainWindow_ProfilesControl_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string MainWindow_ProfilesControl_Delete {
            get {
                return ResourceManager.GetString("MainWindow_ProfilesControl_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter.
        /// </summary>
        public static string MainWindow_ProfilesControl_FilterPlaceholder {
            get {
                return ResourceManager.GetString("MainWindow_ProfilesControl_FilterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string MainWindow_ProfilesControl_Save {
            get {
                return ResourceManager.GetString("MainWindow_ProfilesControl_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save all.
        /// </summary>
        public static string MainWindow_ProfilesControl_SaveAll {
            get {
                return ResourceManager.GetString("MainWindow_ProfilesControl_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        public static string MainWindow_ProfilesInformationGroup_Header {
            get {
                return ResourceManager.GetString("MainWindow_ProfilesInformationGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile name:.
        /// </summary>
        public static string MainWindow_ProfilesInformationGroup_Name {
            get {
                return ResourceManager.GetString("MainWindow_ProfilesInformationGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable Chromium sandbox.
        /// </summary>
        public static string MainWindow_ProfilesOther_ChromiumSandbox {
            get {
                return ResourceManager.GetString("MainWindow_ProfilesOther_ChromiumSandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other.
        /// </summary>
        public static string MainWindow_ProfilesOther_Header {
            get {
                return ResourceManager.GetString("MainWindow_ProfilesOther_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Headless mode.
        /// </summary>
        public static string MainWindow_ProfilesOther_HeadlessMode {
            get {
                return ResourceManager.GetString("MainWindow_ProfilesOther_HeadlessMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slow motion (milliseconds).
        /// </summary>
        public static string MainWindow_ProfilesOther_SlowMo {
            get {
                return ResourceManager.GetString("MainWindow_ProfilesOther_SlowMo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of profiles:.
        /// </summary>
        public static string MainWindow_ProfilesStatus_ProfilesCount {
            get {
                return ResourceManager.GetString("MainWindow_ProfilesStatus_ProfilesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected profile:.
        /// </summary>
        public static string MainWindow_ProfilesStatus_SelectedProfile {
            get {
                return ResourceManager.GetString("MainWindow_ProfilesStatus_SelectedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accept all downloads.
        /// </summary>
        public static string MainWindow_ProfilesStorageGroup_AcceptDownloads {
            get {
                return ResourceManager.GetString("MainWindow_ProfilesStorageGroup_AcceptDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download path.
        /// </summary>
        public static string MainWindow_ProfilesStorageGroup_DownloadPath {
            get {
                return ResourceManager.GetString("MainWindow_ProfilesStorageGroup_DownloadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Storage.
        /// </summary>
        public static string MainWindow_ProfilesStorageGroup_Header {
            get {
                return ResourceManager.GetString("MainWindow_ProfilesStorageGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profiles.
        /// </summary>
        public static string MainWindow_ProfilesTab_Header {
            get {
                return ResourceManager.GetString("MainWindow_ProfilesTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bot:.
        /// </summary>
        public static string MainWindow_RunningTasksGroup_Bot {
            get {
                return ResourceManager.GetString("MainWindow_RunningTasksGroup_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count:.
        /// </summary>
        public static string MainWindow_RunningTasksGroup_BrowserProfilesCount {
            get {
                return ResourceManager.GetString("MainWindow_RunningTasksGroup_BrowserProfilesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        public static string MainWindow_RunningTasksGroup_Details {
            get {
                return ResourceManager.GetString("MainWindow_RunningTasksGroup_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Running tasks.
        /// </summary>
        public static string MainWindow_RunningTasksGroup_Header {
            get {
                return ResourceManager.GetString("MainWindow_RunningTasksGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile:.
        /// </summary>
        public static string MainWindow_RunningTasksGroup_UnitBrowserProfile {
            get {
                return ResourceManager.GetString("MainWindow_RunningTasksGroup_UnitBrowserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status:.
        /// </summary>
        public static string MainWindow_RunningTasksGroup_UnitStatus {
            get {
                return ResourceManager.GetString("MainWindow_RunningTasksGroup_UnitStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run.
        /// </summary>
        public static string MainWindow_RunTab_Header {
            get {
                return ResourceManager.GetString("MainWindow_RunTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run task.
        /// </summary>
        public static string MainWindow_RunTaskGroup_Header {
            get {
                return ResourceManager.GetString("MainWindow_RunTaskGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Launch.
        /// </summary>
        public static string MainWindow_RunTaskGroup_Launch {
            get {
                return ResourceManager.GetString("MainWindow_RunTaskGroup_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select bot:.
        /// </summary>
        public static string MainWindow_RunTaskGroup_SelectBot {
            get {
                return ResourceManager.GetString("MainWindow_RunTaskGroup_SelectBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Profiles:.
        /// </summary>
        public static string MainWindow_RunTaskGroup_SelectProfiles {
            get {
                return ResourceManager.GetString("MainWindow_RunTaskGroup_SelectProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data.
        /// </summary>
        public static string MainWindow_SettingsData_Header {
            get {
                return ResourceManager.GetString("MainWindow_SettingsData_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Path to the directory where the data is stored.
        /// </summary>
        public static string MainWindow_SettingsData_Path {
            get {
                return ResourceManager.GetString("MainWindow_SettingsData_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browse...
        /// </summary>
        public static string MainWindow_SettingsData_Search {
            get {
                return ResourceManager.GetString("MainWindow_SettingsData_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browsers and their channels that need to be installed..
        /// </summary>
        public static string MainWindow_SettingsInstalledBrowsers_Description {
            get {
                return ResourceManager.GetString("MainWindow_SettingsInstalledBrowsers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installed browsers.
        /// </summary>
        public static string MainWindow_SettingsInstalledBrowsers_Header {
            get {
                return ResourceManager.GetString("MainWindow_SettingsInstalledBrowsers_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string MainWindow_SettingsTab_Header {
            get {
                return ResourceManager.GetString("MainWindow_SettingsTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sets parameters that affect the display of the user interface..
        /// </summary>
        public static string MainWindow_SettingsUserInterface_Description {
            get {
                return ResourceManager.GetString("MainWindow_SettingsUserInterface_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interface.
        /// </summary>
        public static string MainWindow_SettingsUserInterface_Header {
            get {
                return ResourceManager.GetString("MainWindow_SettingsUserInterface_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string MainWindow_SettingsUserInterface_Language {
            get {
                return ResourceManager.GetString("MainWindow_SettingsUserInterface_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string MainWindow_SettingsUserInterface_Save {
            get {
                return ResourceManager.GetString("MainWindow_SettingsUserInterface_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Playhouse.
        /// </summary>
        public static string MianWindow_Title {
            get {
                return ResourceManager.GetString("MianWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reason for closing the window:.
        /// </summary>
        public static string PageClosedBotActionViewModel_Reason {
            get {
                return ResourceManager.GetString("PageClosedBotActionViewModel_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trigger an unload event.
        /// </summary>
        public static string PageClosedBotActionViewModel_RunBeforeUnload {
            get {
                return ResourceManager.GetString("PageClosedBotActionViewModel_RunBeforeUnload", resourceCulture);
            }
        }
    }
}
