//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playhouse.Settings.Application.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Playhouse.Settings.Application.Resources.Strings.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The web browser &apos;{PropertyValue}&apos; is not supported by the application..
        /// </summary>
        internal static string ApplicationSettingsDTOValidatorBrowserNotSupported {
            get {
                return ResourceManager.GetString("ApplicationSettingsDTOValidatorBrowserNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser collection cannot contain null value..
        /// </summary>
        internal static string ApplicationSettingsDTOValidatorBrowsersContainsNull {
            get {
                return ResourceManager.GetString("ApplicationSettingsDTOValidatorBrowsersContainsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The browser collection is not initialized..
        /// </summary>
        internal static string ApplicationSettingsDTOValidatorBrowsersIsNull {
            get {
                return ResourceManager.GetString("ApplicationSettingsDTOValidatorBrowsersIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The web browser channel &apos;{PropertyValue}&apos; is not supported by the application..
        /// </summary>
        internal static string ApplicationSettingsDTOValidatorChannelNotSupported {
            get {
                return ResourceManager.GetString("ApplicationSettingsDTOValidatorChannelNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The browser&apos;s channels collection cannot contain a null value..
        /// </summary>
        internal static string ApplicationSettingsDTOValidatorChannelsContainsNull {
            get {
                return ResourceManager.GetString("ApplicationSettingsDTOValidatorChannelsContainsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The browser&apos;s channel collection is not initialized..
        /// </summary>
        internal static string ApplicationSettingsDTOValidatorChannelsIsNull {
            get {
                return ResourceManager.GetString("ApplicationSettingsDTOValidatorChannelsIsNull", resourceCulture);
            }
        }
    }
}
