//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playhouse.Core.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Playhouse.Core.Resources.Strings.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expected implementation &quot;{0}&quot; of abstract type &quot;{1}&quot; but received &quot;{2}&quot;..
        /// </summary>
        internal static string BotJob_IncorrectImplementation {
            get {
                return ResourceManager.GetString("BotJob_IncorrectImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The action performed by the user in the browser is not supported..
        /// </summary>
        internal static string Constructor_NotSupportedAction {
            get {
                return ResourceManager.GetString("Constructor_NotSupportedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The start command was called for a bot construction process that had already completed..
        /// </summary>
        internal static string Constructor_RunCompletedConstruction {
            get {
                return ResourceManager.GetString("Constructor_RunCompletedConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The start command was called for a bot construction process that was already running..
        /// </summary>
        internal static string Constructor_RunRunningConstructor {
            get {
                return ResourceManager.GetString("Constructor_RunRunningConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The stop command was called for a bot construction process that has already completed..
        /// </summary>
        internal static string Constructor_StopCompletedConstruction {
            get {
                return ResourceManager.GetString("Constructor_StopCompletedConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The stop command was called for a bot construction process that was not running..
        /// </summary>
        internal static string Constructor_StopUnrunningConstruction {
            get {
                return ResourceManager.GetString("Constructor_StopUnrunningConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser {0} is not supported..
        /// </summary>
        internal static string PlaywrightFactory_UnsupportedBrowser {
            get {
                return ResourceManager.GetString("PlaywrightFactory_UnsupportedBrowser", resourceCulture);
            }
        }
    }
}
